# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "2Creative Productivity Tool"
  port = 8910
  apiUrl = "/.netlify/functions"
  includeEnvironmentVariables = ["SMTP_USER"]

[api]
  port = 8911

[browser]
  open = true

[generate]
  tests = true
  stories = true

[notifications]
  versionUpdates = ["latest"]
